# CMake generated Testfile for 
# Source directory: /home/saratt/Documents/openML/src/util/eigenCppLibrary/unsupported/test
# Build directory: /home/saratt/Documents/openML/src/util/eigenCppLibrary/eigenRelease/unsupported/test
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(NumericalDiff "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "NumericalDiff")
ADD_TEST(autodiff "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "autodiff")
ADD_TEST(BVH_1 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "BVH_1")
ADD_TEST(BVH_2 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "BVH_2")
ADD_TEST(BVH_3 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "BVH_3")
ADD_TEST(matrix_exponential_2 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_exponential_2")
ADD_TEST(matrix_exponential_1 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_exponential_1")
ADD_TEST(matrix_exponential_8 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_exponential_8")
ADD_TEST(matrix_exponential_6 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_exponential_6")
ADD_TEST(matrix_exponential_5 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_exponential_5")
ADD_TEST(matrix_exponential_7 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_exponential_7")
ADD_TEST(matrix_exponential_3 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_exponential_3")
ADD_TEST(matrix_exponential_4 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_exponential_4")
ADD_TEST(matrix_exponential_9 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_exponential_9")
ADD_TEST(matrix_function_1 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_function_1")
ADD_TEST(matrix_function_2 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_function_2")
ADD_TEST(matrix_function_3 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_function_3")
ADD_TEST(matrix_function_4 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_function_4")
ADD_TEST(matrix_function_5 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_function_5")
ADD_TEST(matrix_function_6 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_function_6")
ADD_TEST(matrix_function_7 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_function_7")
ADD_TEST(matrix_square_root_1 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_square_root_1")
ADD_TEST(matrix_square_root_2 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_square_root_2")
ADD_TEST(matrix_square_root_3 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_square_root_3")
ADD_TEST(matrix_square_root_4 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_square_root_4")
ADD_TEST(matrix_square_root_5 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "matrix_square_root_5")
ADD_TEST(alignedvector3 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "alignedvector3")
ADD_TEST(FFT "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "FFT")
ADD_TEST(sparse_extra_1 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "sparse_extra_1")
ADD_TEST(sparse_extra_2 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "sparse_extra_2")
ADD_TEST(sparse_extra_3 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "sparse_extra_3")
ADD_TEST(polynomialsolver_1 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "polynomialsolver_1")
ADD_TEST(polynomialsolver_2 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "polynomialsolver_2")
ADD_TEST(polynomialsolver_3 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "polynomialsolver_3")
ADD_TEST(polynomialsolver_4 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "polynomialsolver_4")
ADD_TEST(polynomialsolver_5 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "polynomialsolver_5")
ADD_TEST(polynomialsolver_6 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "polynomialsolver_6")
ADD_TEST(polynomialsolver_7 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "polynomialsolver_7")
ADD_TEST(polynomialsolver_8 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "polynomialsolver_8")
ADD_TEST(polynomialsolver_9 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "polynomialsolver_9")
ADD_TEST(polynomialsolver_10 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "polynomialsolver_10")
ADD_TEST(polynomialutils_2 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "polynomialutils_2")
ADD_TEST(polynomialutils_3 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "polynomialutils_3")
ADD_TEST(polynomialutils_4 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "polynomialutils_4")
ADD_TEST(polynomialutils_5 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "polynomialutils_5")
ADD_TEST(polynomialutils_6 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "polynomialutils_6")
ADD_TEST(polynomialutils_7 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "polynomialutils_7")
ADD_TEST(polynomialutils_8 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "polynomialutils_8")
ADD_TEST(polynomialutils_9 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "polynomialutils_9")
ADD_TEST(kronecker_product "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "kronecker_product")
ADD_TEST(splines "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "splines")
ADD_TEST(gmres_1 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "gmres_1")
ADD_TEST(gmres_2 "/home/saratt/Documents/openML/src/util/eigenCppLibrary/test/runtest.sh" "gmres_2")
